# -*- python -*-
Import("env")
import os, re, sys

import lsst.tests
import eups
#
# Tests
#
tests = lsst.tests.Control(env, verbose=True)

dataDir = eups.productDir("afwdata")
if not dataDir:
    print "Warning: afwdata is not set up; not running the tests!"
else:
    # set up python tests
    for target in tests.run("*.py"):
        for pkgName in ("rgb", ):
            env.Depends(target, os.path.join("#python", "lsst", "afw", "extensions", pkgName,
                                             "_%sLib%s" % (pkgName, env["LDMODULESUFFIX"])))
