# -*- python -*-
import glob, os, re

Import('env')
#
# Here's a way to to build the files in the list noOptFiles without optimisation
#
ccFiles = glob.glob("../src/*.cc") + glob.glob("../src/*/*.cc") + glob.glob("../src/*/*/*.cc")
try:
    ccFiles = env.SourcesForSharedLibrary(ccFiles)
except AttributeError:                  # requires sconsUtils > 3.3
    pass

env.SharedLibrary(
    env["eups_product"], ccFiles,
    LIBS=[l for l in env.getlibs(env["eups_product"]) if l != env["eups_product"]]
)
